version: '3.3'

services:
  collaboration-server:
      image: lca-server
      container_name: lca-server
      restart: 'no'
      environment:
        DB_INSTALL: ${DB_INSTALL}
      ports:
        - '8080:8080'
      expose:
        - '8080'
      depends_on:
        collaboration-server-db:
          condition: service_healthy

  collaboration-server-db:
    image: mysql
    container_name: collaboration-server-db  
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'collaboration-server'
      MYSQL_USER: 'collaboration-server'
      MYSQL_PASSWORD: 'collaboration-server'
      MYSQL_ROOT_PASSWORD: 'collaboration-server'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 20
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: